#!/bin/bash

set -e -u
set -o pipefail

export PATH=$PATH:$GOPATH/bin

creds_path=/tmp/creds.yml
manifest_path=$PWD/fixtures/cf-deployment/cf-deployment.yml

go install github.com/rosenhouse/cf-filler

cf-filler -recipe recipe-cf-deployment.yml > $creds_path

bosh-cli build-manifest --var-errs --var-file=$creds_path $manifest_path
